apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chrome-136
spec:
  deployed: true
  powDifficultySeconds: 1
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: eu.gcr.io/gctf-vrp/chrome-136-healthcheck:35ae290bf50914e692e9cf4f97a1cc3f3eb2b89107d2a738c63c03522e9d1f1b
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag
                mountPath: /chroot/flag
                readOnly: true
        volumes:
          - name: flag
            secret:
              defaultMode: 0555
              secretName: v8ctf-flag
              optional: true
  image: eu.gcr.io/gctf-vrp/chrome-136-challenge:23ed30f67d39d5b6f7e040f4df901df68d78a0f3302c3a3f37c39383de3d53da
